#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features="cxx test",
    source=["platform_tests.cpp"] + bld.path.ant_glob("src/*.cpp"),
    target="platform_tests",
    use=["platform_includes", "gtest", "cli11"],
)
