concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  cxx_mkspec:
    name: Apple Big Sur (ARM)
    runs-on:
    - self-hosted
    - macOS
    - ARM64
    - builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: python3 waf configure --git_protocol=git@ $EXTRA_RESOLVE_OPTIONS
    - name: Build
      run: 'echo "::add-matcher::.github/gcc-problem-matcher.json"

        python3 waf

        '
    - name: Test
      run: python3 waf --run_tests --run_cmd="%s --os=mac --compiler=clang --arch=arm"
name: MacOS C++ make-specs
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
