name: No Assertions
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request: null
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.resolve_options }}
jobs:
  ndebug:
    container:
      image: ghcr.io/steinwurf/gcc-11.2.0:1.0.0
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    env:
      test_arch: x86_64
      test_compiler: gcc
      test_os: linux
    name: No Assertions
    runs-on:
    - self-hosted
    - docker
    - builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - env:
        GIT_SSH_COMMAND: ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes
      name: Configure
      run: python3 waf configure --cxx_nodebug --git_protocol=git@ $EXTRA_RESOLVE_OPTIONS
    - name: Build
      run: 'echo "::add-matcher::.github/gcc-problem-matcher.json"

        python3 waf

        '
    - name: Test
      run: python3 waf --run_tests --run_cmd="%s --os=${{env.test_os}} --compiler=${{env.test_compiler}}
        --arch=${{env.test_arch}}"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
